//go:build ignore

// generate-paper-tables reads benchmark results and emits LaTeX table fragments.
// Usage: go run scripts/generate-paper-tables.go [-results results/]
package main

import (
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	resultsDir := flag.String("results", "results", "path to results directory")
	tablesDir := flag.String("tables", "paper/tables", "path to paper/tables output directory")
	flag.Parse()

	if err := os.MkdirAll(*tablesDir, 0o755); err != nil {
		fatal(err)
	}

	if err := generateCLITable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: CLI table: %v\n", err)
	}
	if err := generateStatsTable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: stats table: %v\n", err)
	}
	if err := generateAPITable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: API table: %v\n", err)
	}

	fmt.Println("Paper tables generated.")
}

func generateCLITable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-cli-summary.csv")
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	r := csv.NewReader(f)
	rows, err := r.ReadAll()
	if err != nil {
		return err
	}
	if len(rows) < 2 {
		return fmt.Errorf("no data in %s", path)
	}

	h := indexHeader(rows[0])

	type key struct{ workload, mode string }
	type val struct{ impl string; avgMS float64 }
	data := map[key][]val{}

	for _, row := range rows[1:] {
		cls := row[h["class"]]
		if cls != "valid" {
			continue
		}
		k := key{workload: row[h["workload"]], mode: row[h["mode"]]}
		ms, _ := strconv.ParseFloat(row[h["avg_ms"]], 64)
		data[k] = append(data[k], val{impl: row[h["impl"]], avgMS: ms})
	}

	keys := make([]key, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].workload == keys[j].workload {
			return keys[i].mode < keys[j].mode
		}
		return keys[i].workload < keys[j].workload
	})

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table}[htbp]\n")
	b.WriteString("\\caption{CLI benchmark results (end-to-end, $n=15$).}\n")
	b.WriteString("\\label{tab:cli-benchmarks}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{llrrrr}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Workload & Mode & Schubfach (ms) & json-canon (ms) & Speedup & Winner \\\\\n")
	b.WriteString("\\midrule\n")

	for _, k := range keys {
		vs := data[k]
		var schub, jc float64
		for _, v := range vs {
			switch v.impl {
			case "schubfach":
				schub = v.avgMS
			case "json-canon":
				jc = v.avgMS
			}
		}
		if schub == 0 || jc == 0 {
			continue
		}
		winner := "schubfach"
		speedup := jc / schub
		if jc < schub {
			winner = "json-canon"
			speedup = schub / jc
		}
		fmt.Fprintf(&b, "%s & %s & %.3f & %.3f & %.2f$\\times$ & %s \\\\\n",
			escape(k.workload), k.mode, schub, jc, speedup, winner)
	}

	b.WriteString("\\bottomrule\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table}\n")

	return os.WriteFile(filepath.Join(tablesDir, "cli-benchmarks.tex"), []byte(b.String()), 0o644)
}

func generateStatsTable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-stats.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	var report struct {
		Comparisons []struct {
			Track               string  `json:"track"`
			Mode                string  `json:"mode"`
			Workload            string  `json:"workload"`
			Winner              string  `json:"winner"`
			Speedup             float64 `json:"speedup"`
			CI95Low             float64 `json:"ci95_low"`
			CI95High            float64 `json:"ci95_high"`
			PValue              float64 `json:"p_value"`
			PValueAdjusted      float64 `json:"p_value_adjusted"`
			EffectSizeCohenD    float64 `json:"effect_size_cohen_d"`
			Significant         bool    `json:"significant"`
			SignificantBH       bool    `json:"significant_bh"`
			NoiseFloorMS        float64 `json:"noise_floor_ms"`
			MinObservableEffPct float64 `json:"min_observable_effect_pct"`
		} `json:"comparisons"`
	}
	if err := json.Unmarshal(data, &report); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table*}[htbp]\n")
	b.WriteString("\\caption{Statistical comparisons with Benjamini-Hochberg corrected $p$-values.}\n")
	b.WriteString("\\label{tab:stats-comparisons}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{llllrrrrrrl}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Track & Mode & Workload & Winner & Speedup & CI$_{95}$ & $p$ & $p_\\text{adj}$ & $d$ & Noise (ms) & Min.\\ Eff.\\ (\\%) \\\\\n")
	b.WriteString("\\midrule\n")

	for _, c := range report.Comparisons {
		sig := ""
		if c.SignificantBH {
			sig = "$^*$"
		}
		fmt.Fprintf(&b, "%s & %s & %s & %s%s & %.2f$\\times$ & [%.3f, %.3f] & %.4f & %.4f & %.2f & %.4f & %.1f \\\\\n",
			c.Track, c.Mode, escape(c.Workload), c.Winner, sig, c.Speedup,
			c.CI95Low, c.CI95High, c.PValue, c.PValueAdjusted, c.EffectSizeCohenD,
			c.NoiseFloorMS, c.MinObservableEffPct)
	}

	b.WriteString("\\bottomrule\n")
	b.WriteString("\\multicolumn{11}{l}{\\footnotesize $^*$Significant after Benjamini-Hochberg FDR correction at $q = 0.05$.} \\\\\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table*}\n")

	return os.WriteFile(filepath.Join(tablesDir, "stats-comparisons.tex"), []byte(b.String()), 0o644)
}

func generateAPITable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-api-bench.txt")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	type benchLine struct {
		name   string
		nsOp   float64
		bOp    float64
		allocN float64
	}
	var lines []benchLine
	for _, line := range strings.Split(string(data), "\n") {
		if !strings.HasPrefix(line, "Benchmark") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 3 {
			continue
		}
		bl := benchLine{name: fields[0]}
		for i := 1; i < len(fields)-1; i++ {
			switch fields[i+1] {
			case "ns/op":
				bl.nsOp, _ = strconv.ParseFloat(fields[i], 64)
			case "B/op":
				bl.bOp, _ = strconv.ParseFloat(fields[i], 64)
			case "allocs/op":
				bl.allocN, _ = strconv.ParseFloat(fields[i], 64)
			}
		}
		lines = append(lines, bl)
	}

	// Group by benchmark base name (strip iteration suffix) and compute means.
	type benchGroup struct {
		nsOps   []float64
		bOps    []float64
		allocNs []float64
	}
	groups := map[string]*benchGroup{}
	order := []string{}
	for _, l := range lines {
		// Benchmark names from go test -count=N have the form BenchmarkFoo-12 repeated N times.
		name := l.name
		if _, ok := groups[name]; !ok {
			groups[name] = &benchGroup{}
			order = append(order, name)
		}
		g := groups[name]
		g.nsOps = append(g.nsOps, l.nsOp)
		g.bOps = append(g.bOps, l.bOp)
		g.allocNs = append(g.allocNs, l.allocN)
	}

	// Parse into impl+operation pairs for summary.
	type summaryKey struct {
		workload string
		mode     string
	}
	type implMetrics struct {
		nsOp   float64
		bOp    float64
		allocN float64
	}
	summaryData := map[summaryKey]map[string]implMetrics{}
	summaryOrder := []summaryKey{}

	for _, name := range order {
		g := groups[name]
		meanNS := mean(g.nsOps)
		meanB := mean(g.bOps)
		meanAlloc := mean(g.allocNs)

		// Parse name: BenchmarkCanonicalize_workload/impl-N or BenchmarkVerify_workload/impl-N
		base := name
		if idx := strings.LastIndex(base, "-"); idx > 0 {
			// Strip -N CPU suffix.
			if _, err := strconv.Atoi(base[idx+1:]); err == nil {
				base = base[:idx]
			}
		}

		var mode, workload, impl string
		if strings.HasPrefix(base, "BenchmarkCanonicalize_") {
			mode = "canonicalize"
			rest := strings.TrimPrefix(base, "BenchmarkCanonicalize_")
			if slashIdx := strings.LastIndex(rest, "/"); slashIdx >= 0 {
				workload = rest[:slashIdx]
				impl = rest[slashIdx+1:]
			} else {
				workload = rest
				impl = "unknown"
			}
		} else if strings.HasPrefix(base, "BenchmarkVerify_") {
			mode = "verify"
			rest := strings.TrimPrefix(base, "BenchmarkVerify_")
			if slashIdx := strings.LastIndex(rest, "/"); slashIdx >= 0 {
				workload = rest[:slashIdx]
				impl = rest[slashIdx+1:]
			} else {
				workload = rest
				impl = "unknown"
			}
		} else {
			continue
		}

		sk := summaryKey{workload: workload, mode: mode}
		if _, ok := summaryData[sk]; !ok {
			summaryData[sk] = map[string]implMetrics{}
			summaryOrder = append(summaryOrder, sk)
		}
		summaryData[sk][impl] = implMetrics{nsOp: meanNS, bOp: meanB, allocN: meanAlloc}
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table*}[htbp]\n")
	b.WriteString("\\caption{API benchmark summary (Go \\texttt{testing.B}, mean of $n=10$ iterations).}\n")
	b.WriteString("\\label{tab:api-benchmarks}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{llrrrrrr}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Workload & Mode & \\multicolumn{2}{c}{ns/op} & Speedup & $\\Delta$allocs/op & $\\Delta$B/op \\\\\n")
	b.WriteString(" & & Schubfach & json-canon & & & \\\\\n")
	b.WriteString("\\midrule\n")

	for _, sk := range summaryOrder {
		impls := summaryData[sk]
		schub, hasS := impls["schubfach"]
		jc, hasJ := impls["json-canon"]
		if !hasS || !hasJ {
			continue
		}

		winner := "schubfach"
		speedup := jc.nsOp / schub.nsOp
		if jc.nsOp < schub.nsOp {
			winner = "json-canon"
			speedup = schub.nsOp / jc.nsOp
		}
		_ = winner

		deltaAllocs := jc.allocN - schub.allocN
		deltaB := jc.bOp - schub.bOp

		fmt.Fprintf(&b, "%s & %s & %.0f & %.0f & %.2f$\\times$ & %+.0f & %+.0f \\\\\n",
			escape(sk.workload), sk.mode,
			schub.nsOp, jc.nsOp, speedup,
			deltaAllocs, deltaB)
	}

	b.WriteString("\\bottomrule\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table*}\n")

	return os.WriteFile(filepath.Join(tablesDir, "api-benchmarks.tex"), []byte(b.String()), 0o644)
}

func mean(xs []float64) float64 {
	if len(xs) == 0 {
		return 0
	}
	var sum float64
	for _, x := range xs {
		sum += x
	}
	return math.Round(sum/float64(len(xs))*100) / 100
}

func indexHeader(row []string) map[string]int {
	m := make(map[string]int, len(row))
	for i, v := range row {
		m[v] = i
	}
	return m
}

func escape(s string) string {
	s = strings.ReplaceAll(s, "_", "\\_")
	s = strings.ReplaceAll(s, "&", "\\&")
	s = strings.ReplaceAll(s, "%", "\\%")
	return s
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}
