//go:build ignore

// generate-paper-tables reads benchmark results and emits LaTeX table fragments.
// Usage: go run scripts/generate-paper-tables.go [-results results/]
package main

import (
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	resultsDir := flag.String("results", "results", "path to results directory")
	tablesDir := flag.String("tables", "paper/tables", "path to paper/tables output directory")
	flag.Parse()

	if err := os.MkdirAll(*tablesDir, 0o755); err != nil {
		fatal(err)
	}

	if err := generateCLITable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: CLI table: %v\n", err)
	}
	if err := generateStatsTable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: stats table: %v\n", err)
	}
	if err := generateAPITable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: API table: %v\n", err)
	}

	fmt.Println("Paper tables generated.")
}

func generateCLITable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-cli-summary.csv")
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	r := csv.NewReader(f)
	rows, err := r.ReadAll()
	if err != nil {
		return err
	}
	if len(rows) < 2 {
		return fmt.Errorf("no data in %s", path)
	}

	h := indexHeader(rows[0])

	type key struct{ workload, mode string }
	type val struct{ impl string; avgMS float64 }
	data := map[key][]val{}

	for _, row := range rows[1:] {
		cls := row[h["class"]]
		if cls != "valid" {
			continue
		}
		k := key{workload: row[h["workload"]], mode: row[h["mode"]]}
		ms, _ := strconv.ParseFloat(row[h["avg_ms"]], 64)
		data[k] = append(data[k], val{impl: row[h["impl"]], avgMS: ms})
	}

	keys := make([]key, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].workload == keys[j].workload {
			return keys[i].mode < keys[j].mode
		}
		return keys[i].workload < keys[j].workload
	})

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table}[htbp]\n")
	b.WriteString("\\caption{CLI benchmark results (end-to-end, $n=15$).}\n")
	b.WriteString("\\label{tab:cli-benchmarks}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{llrrrr}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Workload & Mode & Schubfach (ms) & json-canon (ms) & Speedup & Winner \\\\\n")
	b.WriteString("\\midrule\n")

	for _, k := range keys {
		vs := data[k]
		var schub, jc float64
		for _, v := range vs {
			switch v.impl {
			case "schubfach":
				schub = v.avgMS
			case "json-canon":
				jc = v.avgMS
			}
		}
		if schub == 0 || jc == 0 {
			continue
		}
		winner := "schubfach"
		speedup := jc / schub
		if jc < schub {
			winner = "json-canon"
			speedup = schub / jc
		}
		fmt.Fprintf(&b, "%s & %s & %.3f & %.3f & %.2f$\\times$ & %s \\\\\n",
			escape(k.workload), k.mode, schub, jc, speedup, winner)
	}

	b.WriteString("\\bottomrule\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table}\n")

	return os.WriteFile(filepath.Join(tablesDir, "cli-benchmarks.tex"), []byte(b.String()), 0o644)
}

func generateStatsTable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-stats.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	var report struct {
		Comparisons []struct {
			Track               string  `json:"track"`
			Mode                string  `json:"mode"`
			Workload            string  `json:"workload"`
			Winner              string  `json:"winner"`
			Speedup             float64 `json:"speedup"`
			CI95Low             float64 `json:"ci95_low"`
			CI95High            float64 `json:"ci95_high"`
			PValue              float64 `json:"p_value"`
			EffectSizeCohenD    float64 `json:"effect_size_cohen_d"`
			Significant         bool    `json:"significant"`
			NoiseFloorMS        float64 `json:"noise_floor_ms"`
			MinObservableEffPct float64 `json:"min_observable_effect_pct"`
		} `json:"comparisons"`
	}
	if err := json.Unmarshal(data, &report); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table*}[htbp]\n")
	b.WriteString("\\caption{Statistical comparisons with noise floor and minimum observable effect.}\n")
	b.WriteString("\\label{tab:stats-comparisons}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{llllrrrrrl}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Track & Mode & Workload & Winner & Speedup & CI$_{95}$ & $p$ & $d$ & Noise (ms) & Min.\\ Eff.\\ (\\%) \\\\\n")
	b.WriteString("\\midrule\n")

	for _, c := range report.Comparisons {
		sig := ""
		if c.Significant {
			sig = "$^*$"
		}
		fmt.Fprintf(&b, "%s & %s & %s & %s%s & %.2f$\\times$ & [%.3f, %.3f] & %.4f & %.2f & %.4f & %.1f \\\\\n",
			c.Track, c.Mode, escape(c.Workload), c.Winner, sig, c.Speedup,
			c.CI95Low, c.CI95High, c.PValue, c.EffectSizeCohenD,
			c.NoiseFloorMS, c.MinObservableEffPct)
	}

	b.WriteString("\\bottomrule\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table*}\n")

	return os.WriteFile(filepath.Join(tablesDir, "stats-comparisons.tex"), []byte(b.String()), 0o644)
}

func generateAPITable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-api-bench.txt")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	type benchLine struct {
		name   string
		nsOp   string
		bOp    string
		allocN string
	}
	var lines []benchLine
	for _, line := range strings.Split(string(data), "\n") {
		if !strings.HasPrefix(line, "Benchmark") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 3 {
			continue
		}
		bl := benchLine{name: fields[0]}
		for i := 1; i < len(fields)-1; i++ {
			switch fields[i+1] {
			case "ns/op":
				bl.nsOp = fields[i]
			case "B/op":
				bl.bOp = fields[i]
			case "allocs/op":
				bl.allocN = fields[i]
			}
		}
		lines = append(lines, bl)
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table}[htbp]\n")
	b.WriteString("\\caption{API benchmark results (Go \\texttt{testing.B}, $n=10$).}\n")
	b.WriteString("\\label{tab:api-benchmarks}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{lrrr}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Benchmark & ns/op & B/op & allocs/op \\\\\n")
	b.WriteString("\\midrule\n")
	for _, l := range lines {
		fmt.Fprintf(&b, "\\texttt{%s} & %s & %s & %s \\\\\n",
			escape(l.name), l.nsOp, l.bOp, l.allocN)
	}
	b.WriteString("\\bottomrule\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table}\n")

	return os.WriteFile(filepath.Join(tablesDir, "api-benchmarks.tex"), []byte(b.String()), 0o644)
}

func indexHeader(row []string) map[string]int {
	m := make(map[string]int, len(row))
	for i, v := range row {
		m[v] = i
	}
	return m
}

func escape(s string) string {
	s = strings.ReplaceAll(s, "_", "\\_")
	s = strings.ReplaceAll(s, "&", "\\&")
	s = strings.ReplaceAll(s, "%", "\\%")
	return s
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}
