//go:build ignore

// generate-paper-tables reads benchmark results and emits LaTeX table fragments.
// Usage: go run scripts/generate-paper-tables.go [-results results/]
package main

import (
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type pair struct {
	A     string
	B     string
	Label string
}

func allPairs() []pair {
	return []pair{
		{A: "schubfach", B: "json-canon", Label: "go:schubfach-vs-bd"},
		{A: "schubfach-rs", B: "json-canon-rs", Label: "rs:schubfach-vs-bd"},
		{A: "schubfach", B: "schubfach-rs", Label: "schubfach:go-vs-rs"},
		{A: "json-canon", B: "json-canon-rs", Label: "bd:go-vs-rs"},
	}
}

func main() {
	resultsDir := flag.String("results", "results", "path to results directory")
	tablesDir := flag.String("tables", "paper/tables", "path to paper/tables output directory")
	flag.Parse()

	if err := os.MkdirAll(*tablesDir, 0o755); err != nil {
		fatal(err)
	}

	if err := generateCLITable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: CLI table: %v\n", err)
	}
	if err := generateStatsTable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: stats table: %v\n", err)
	}
	if err := generateAPITable(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: API table: %v\n", err)
	}
	if err := generateAPISummary(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: API summary: %v\n", err)
	}
	if err := generateCLISummary(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: CLI summary: %v\n", err)
	}
	if err := generateStatsSummary(*resultsDir, *tablesDir); err != nil {
		fmt.Fprintf(os.Stderr, "warning: stats summary: %v\n", err)
	}

	fmt.Println("Paper tables generated.")
}

func generateCLITable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-cli-summary.csv")
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	r := csv.NewReader(f)
	rows, err := r.ReadAll()
	if err != nil {
		return err
	}
	if len(rows) < 2 {
		return fmt.Errorf("no data in %s", path)
	}

	h := indexHeader(rows[0])

	type key struct{ workload, mode string }
	data := map[key]map[string]float64{}

	for _, row := range rows[1:] {
		cls := row[h["class"]]
		if cls != "valid" {
			continue
		}
		k := key{workload: row[h["workload"]], mode: row[h["mode"]]}
		ms, _ := strconv.ParseFloat(row[h["avg_ms"]], 64)
		if _, ok := data[k]; !ok {
			data[k] = map[string]float64{}
		}
		data[k][row[h["impl"]]] = ms
	}

	keys := make([]key, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].workload == keys[j].workload {
			return keys[i].mode < keys[j].mode
		}
		return keys[i].workload < keys[j].workload
	})

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\scriptsize\n")
	b.WriteString("\\begin{longtable}{lllrrrr}\n")
	b.WriteString("\\caption{CLI benchmark results (end-to-end, $n=15$).}\n")
	b.WriteString("\\label{tab:cli-benchmarks}\\\\\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Workload & Mode & Impl A (ms) & Impl B (ms) & Speedup & Winner \\\\\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\endfirsthead\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Workload & Mode & Impl A (ms) & Impl B (ms) & Speedup & Winner \\\\\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\endhead\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\multicolumn{7}{r}{\\textit{Continued on next page}} \\\\\n")
	b.WriteString("\\endfoot\n")
	b.WriteString("\\bottomrule\n")
	b.WriteString("\\multicolumn{7}{l}{\\footnotesize Speedup = slower/faster mean wall time. $n=15$ repetitions, 3 warmup runs discarded.} \\\\\n")
	b.WriteString("\\endlastfoot\n")

	for _, p := range allPairs() {
		for _, k := range keys {
			implA := data[k][p.A]
			implB := data[k][p.B]
			if implA == 0 || implB == 0 {
				continue
			}
			winner := p.A
			speedup := implB / implA
			if implB < implA {
				winner = p.B
				speedup = implA / implB
			}
			fmt.Fprintf(&b, "%s & %s & %s & %.3f & %.3f & %.2f$\\times$ & %s \\\\\n",
				escape(p.Label), escape(k.workload), k.mode, implA, implB, speedup, winner)
		}
	}

	b.WriteString("\\end{longtable}\n")
	b.WriteString("\\normalsize\n")

	return os.WriteFile(filepath.Join(tablesDir, "cli-benchmarks.tex"), []byte(b.String()), 0o644)
}

func generateStatsTable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-stats.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	var report struct {
		Comparisons []struct {
			PairLabel           string  `json:"pair_label"`
			Track               string  `json:"track"`
			Mode                string  `json:"mode"`
			Workload            string  `json:"workload"`
			ImplA               string  `json:"impl_a"`
			ImplB               string  `json:"impl_b"`
			Winner              string  `json:"winner"`
			Speedup             float64 `json:"speedup"`
			CI95Low             float64 `json:"ci95_low"`
			CI95High            float64 `json:"ci95_high"`
			PValue              float64 `json:"p_value"`
			PValueAdjusted      float64 `json:"p_value_adjusted"`
			EffectSizeCohenD    float64 `json:"effect_size_cohen_d"`
			Significant         bool    `json:"significant"`
			SignificantBH       bool    `json:"significant_bh"`
			NoiseFloorMS        float64 `json:"noise_floor_ms"`
			MinObservableEffPct float64 `json:"min_observable_effect_pct"`
		} `json:"comparisons"`
	}
	if err := json.Unmarshal(data, &report); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\scriptsize\n")
	b.WriteString("\\begin{longtable}{lllllllrlrrrrr}\n")
	b.WriteString("\\caption{Statistical comparisons with Benjamini-Hochberg corrected $p$-values.}\n")
	b.WriteString("\\label{tab:stats-comparisons}\\\\\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Track & Mode & Workload & Impl A & Impl B & Winner & Speedup & CI$_{95}$ & $p$ & $p_\\text{adj}$ & $d$ & Noise (ms) & MDE (\\%) \\\\\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\endfirsthead\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Track & Mode & Workload & Impl A & Impl B & Winner & Speedup & CI$_{95}$ & $p$ & $p_\\text{adj}$ & $d$ & Noise (ms) & MDE (\\%) \\\\\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\endhead\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\multicolumn{14}{r}{\\textit{Continued on next page}} \\\\\n")
	b.WriteString("\\endfoot\n")
	b.WriteString("\\bottomrule\n")
	b.WriteString("\\multicolumn{14}{l}{\\footnotesize $^*$Significant after Benjamini-Hochberg FDR correction at $q = 0.05$.} \\\\\n")
	b.WriteString("\\multicolumn{14}{l}{\\footnotesize $d$ = Cohen's $d$: $(\\bar{x}_A - \\bar{x}_B)/s_p$; negative = impl A faster. Track: e2e = end-to-end CLI.} \\\\\n")
	b.WriteString("\\multicolumn{14}{l}{\\footnotesize Noise = CV $\\times$ mean of faster impl. MDE = minimum detectable effect at 80\\% power ($z$-approx).} \\\\\n")
	b.WriteString("\\multicolumn{14}{l}{\\footnotesize Rust allocs/op and B/op report 0 (not measured); see \\S\\ref{sec:discussion}.} \\\\\n")
	b.WriteString("\\endlastfoot\n")

	for _, c := range report.Comparisons {
		sig := ""
		if c.SignificantBH {
			sig = "$^*$"
		}
		fmt.Fprintf(&b, "%s & %s & %s & %s & %s & %s & %s%s & %.2f$\\times$ & [%.3f, %.3f] & %.4f & %.4f & %.2f & %.4f & %.1f \\\\\n",
			escape(c.PairLabel), c.Track, c.Mode, escape(c.Workload), c.ImplA, c.ImplB, c.Winner, sig, c.Speedup,
			c.CI95Low, c.CI95High, c.PValue, c.PValueAdjusted, c.EffectSizeCohenD,
			c.NoiseFloorMS, c.MinObservableEffPct)
	}

	b.WriteString("\\end{longtable}\n")
	b.WriteString("\\normalsize\n")

	return os.WriteFile(filepath.Join(tablesDir, "stats-comparisons.tex"), []byte(b.String()), 0o644)
}

func generateAPITable(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-api-bench.txt")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	type benchLine struct {
		name   string
		nsOp   float64
		bOp    float64
		allocN float64
	}
	var lines []benchLine
	for _, line := range strings.Split(string(data), "\n") {
		if !strings.HasPrefix(line, "Benchmark") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 3 {
			continue
		}
		bl := benchLine{name: fields[0]}
		for i := 1; i < len(fields)-1; i++ {
			switch fields[i+1] {
			case "ns/op":
				bl.nsOp, _ = strconv.ParseFloat(fields[i], 64)
			case "B/op":
				bl.bOp, _ = strconv.ParseFloat(fields[i], 64)
			case "allocs/op":
				bl.allocN, _ = strconv.ParseFloat(fields[i], 64)
			}
		}
		lines = append(lines, bl)
	}

	// Group by benchmark base name (strip iteration suffix) and compute means.
	type benchGroup struct {
		nsOps   []float64
		bOps    []float64
		allocNs []float64
	}
	groups := map[string]*benchGroup{}
	order := []string{}
	for _, l := range lines {
		// Benchmark names from go test -count=N have the form BenchmarkFoo-12 repeated N times.
		name := l.name
		if _, ok := groups[name]; !ok {
			groups[name] = &benchGroup{}
			order = append(order, name)
		}
		g := groups[name]
		g.nsOps = append(g.nsOps, l.nsOp)
		g.bOps = append(g.bOps, l.bOp)
		g.allocNs = append(g.allocNs, l.allocN)
	}

	// Parse into impl+operation pairs for summary.
	type summaryKey struct {
		workload string
		mode     string
	}
	type implMetrics struct {
		nsOp   float64
		bOp    float64
		allocN float64
	}
	summaryData := map[summaryKey]map[string]implMetrics{}
	summaryOrder := []summaryKey{}

	for _, name := range order {
		g := groups[name]
		meanNS := mean(g.nsOps)
		meanB := mean(g.bOps)
		meanAlloc := mean(g.allocNs)

		// Parse name: BenchmarkAPICanonicalizeSchubfach/workload-N
		parts := strings.SplitN(name, "/", 2)
		if len(parts) != 2 {
			continue
		}
		impl, mode, ok := parseBenchPrefix(parts[0])
		if !ok {
			continue
		}
		workload := trimCPUSuffix(parts[1])

		sk := summaryKey{workload: workload, mode: mode}
		if _, ok := summaryData[sk]; !ok {
			summaryData[sk] = map[string]implMetrics{}
			summaryOrder = append(summaryOrder, sk)
		}
		summaryData[sk][impl] = implMetrics{nsOp: meanNS, bOp: meanB, allocN: meanAlloc}
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\scriptsize\n")
	b.WriteString("\\begin{longtable}{lllrrrrr}\n")
	b.WriteString("\\caption{API benchmark results (mean of $n=10$ iterations).}\n")
	b.WriteString("\\label{tab:api-benchmarks}\\\\\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Workload & Mode & \\multicolumn{2}{c}{ns/op} & Speedup & $\\Delta$allocs/op & $\\Delta$B/op \\\\\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\endfirsthead\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Workload & Mode & \\multicolumn{2}{c}{ns/op} & Speedup & $\\Delta$allocs/op & $\\Delta$B/op \\\\\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\endhead\n")
	b.WriteString("\\midrule\n")
	b.WriteString("\\multicolumn{8}{r}{\\textit{Continued on next page}} \\\\\n")
	b.WriteString("\\endfoot\n")
	b.WriteString("\\bottomrule\n")
	b.WriteString("\\multicolumn{8}{l}{\\footnotesize B/op = bytes allocated per operation. allocs/op = heap allocations per operation.} \\\\\n")
	b.WriteString("\\multicolumn{8}{l}{\\footnotesize $\\Delta$ columns show Impl B $-$ Impl A for each pair.} \\\\\n")
	b.WriteString("\\endlastfoot\n")

	for _, p := range allPairs() {
		for _, sk := range summaryOrder {
			impls := summaryData[sk]
			implA, hasA := impls[p.A]
			implB, hasB := impls[p.B]
			if !hasA || !hasB {
				continue
			}
			speedup := implB.nsOp / implA.nsOp
			if implB.nsOp < implA.nsOp {
				speedup = implA.nsOp / implB.nsOp
			}
			deltaAllocs := implB.allocN - implA.allocN
			deltaB := implB.bOp - implA.bOp
			fmt.Fprintf(&b, "%s & %s & %s & %.0f & %.0f & %.2f$\\times$ & %+.0f & %+.0f \\\\\n",
				escape(p.Label), escape(sk.workload), sk.mode,
				implA.nsOp, implB.nsOp, speedup,
				deltaAllocs, deltaB)
		}
	}

	b.WriteString("\\end{longtable}\n")
	b.WriteString("\\normalsize\n")

	return os.WriteFile(filepath.Join(tablesDir, "api-benchmarks.tex"), []byte(b.String()), 0o644)
}

// --- Summary table generators ---

// summaryWorkloads are the representative subset shown in the main text.
var summaryWorkloads = map[string]bool{
	"array-2048":       true,
	"array-256":        true,
	"large":            true,
	"medium":           true,
	"numeric-boundary":  true,
	"number-heavy":     true,
	"mixed-prod":       true,
	"small":            true,
	"deep":             true,
	"deep-64":          true,
	"long-string":      true,
	"unicode":          true,
	"control-escapes":  true,
	"rfc-key-sorting":  true,
	"verify-whitespace": true,
}

func generateAPISummary(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-api-bench.txt")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	type benchLine struct {
		name string
		nsOp float64
		bOp  float64
	}
	var lines []benchLine
	for _, line := range strings.Split(string(data), "\n") {
		if !strings.HasPrefix(line, "Benchmark") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 3 {
			continue
		}
		bl := benchLine{name: fields[0]}
		for i := 1; i < len(fields)-1; i++ {
			switch fields[i+1] {
			case "ns/op":
				bl.nsOp, _ = strconv.ParseFloat(fields[i], 64)
			case "B/op":
				bl.bOp, _ = strconv.ParseFloat(fields[i], 64)
			}
		}
		lines = append(lines, bl)
	}

	type benchGroup struct{ nsOps []float64 }
	groups := map[string]*benchGroup{}
	order := []string{}
	for _, l := range lines {
		if _, ok := groups[l.name]; !ok {
			groups[l.name] = &benchGroup{}
			order = append(order, l.name)
		}
		groups[l.name].nsOps = append(groups[l.name].nsOps, l.nsOp)
	}

	type summaryKey struct{ workload, mode string }
	summaryData := map[summaryKey]map[string]float64{}
	summaryOrder := []summaryKey{}

	for _, name := range order {
		g := groups[name]
		meanNS := mean(g.nsOps)
		parts := strings.SplitN(name, "/", 2)
		if len(parts) != 2 {
			continue
		}
		impl, mode, ok := parseBenchPrefix(parts[0])
		if !ok {
			continue
		}
		workload := trimCPUSuffix(parts[1])
		sk := summaryKey{workload: workload, mode: mode}
		if _, ok := summaryData[sk]; !ok {
			summaryData[sk] = map[string]float64{}
			summaryOrder = append(summaryOrder, sk)
		}
		summaryData[sk][impl] = meanNS
		_ = impl
	}

	// Only within-language pairs, canonicalize mode, summary workloads.
	withinPairs := []pair{
		{A: "schubfach", B: "json-canon", Label: "go:schubfach-vs-bd"},
		{A: "schubfach-rs", B: "json-canon-rs", Label: "rs:schubfach-vs-bd"},
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table}[htbp]\n")
	b.WriteString("\\caption{API benchmark summary: within-language algorithm comparisons (canonicalize mode, mean of $n{=}10$).}\n")
	b.WriteString("\\label{tab:api-summary}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{llrrr}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Workload & \\schubfach (ns/op) & \\burgerdybvig (ns/op) & Speedup \\\\\n")
	b.WriteString("\\midrule\n")

	for _, p := range withinPairs {
		for _, sk := range summaryOrder {
			if sk.mode != "canonicalize" {
				continue
			}
			if !summaryWorkloads[sk.workload] {
				continue
			}
			implA := summaryData[sk][p.A]
			implB := summaryData[sk][p.B]
			if implA == 0 || implB == 0 {
				continue
			}
			speedup := implB / implA
			if implB < implA {
				speedup = implA / implB
			}
			fmt.Fprintf(&b, "%s & %s & %.0f & %.0f & %.2f$\\times$ \\\\\n",
				escape(p.Label), escape(sk.workload), implA, implB, speedup)
		}
	}

	b.WriteString("\\bottomrule\n")
	b.WriteString("\\multicolumn{5}{l}{\\footnotesize Full results for all pairs, modes, and workloads in Appendix~\\ref{sec:appendix-tables}.} \\\\\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table}\n")

	return os.WriteFile(filepath.Join(tablesDir, "api-summary.tex"), []byte(b.String()), 0o644)
}

func generateCLISummary(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-cli-summary.csv")
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	r := csv.NewReader(f)
	rows, err := r.ReadAll()
	if err != nil {
		return err
	}
	if len(rows) < 2 {
		return fmt.Errorf("no data in %s", path)
	}
	h := indexHeader(rows[0])

	type key struct{ workload, mode string }
	data := map[key]map[string]float64{}
	for _, row := range rows[1:] {
		if row[h["class"]] != "valid" {
			continue
		}
		k := key{workload: row[h["workload"]], mode: row[h["mode"]]}
		ms, _ := strconv.ParseFloat(row[h["avg_ms"]], 64)
		if _, ok := data[k]; !ok {
			data[k] = map[string]float64{}
		}
		data[k][row[h["impl"]]] = ms
	}

	keys := make([]key, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].workload == keys[j].workload {
			return keys[i].mode < keys[j].mode
		}
		return keys[i].workload < keys[j].workload
	})

	// Only within-language pairs, canonicalize mode.
	withinPairs := []pair{
		{A: "schubfach", B: "json-canon", Label: "go:schubfach-vs-bd"},
		{A: "schubfach-rs", B: "json-canon-rs", Label: "rs:schubfach-vs-bd"},
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table}[htbp]\n")
	b.WriteString("\\caption{CLI benchmark summary: within-language comparisons (canonicalize mode, $n{=}15$, 3 warmup discarded).}\n")
	b.WriteString("\\label{tab:cli-summary}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{llrrrr}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Workload & Impl A (ms) & Impl B (ms) & Speedup & Winner \\\\\n")
	b.WriteString("\\midrule\n")

	for _, p := range withinPairs {
		for _, k := range keys {
			if k.mode != "canonicalize" {
				continue
			}
			implA := data[k][p.A]
			implB := data[k][p.B]
			if implA == 0 || implB == 0 {
				continue
			}
			winner := p.A
			speedup := implB / implA
			if implB < implA {
				winner = p.B
				speedup = implA / implB
			}
			fmt.Fprintf(&b, "%s & %s & %.3f & %.3f & %.2f$\\times$ & %s \\\\\n",
				escape(p.Label), escape(k.workload), implA, implB, speedup, winner)
		}
	}

	b.WriteString("\\bottomrule\n")
	b.WriteString("\\multicolumn{6}{l}{\\footnotesize Full results including verify mode and cross-language pairs in Appendix~\\ref{sec:appendix-tables}.} \\\\\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table}\n")

	return os.WriteFile(filepath.Join(tablesDir, "cli-summary.tex"), []byte(b.String()), 0o644)
}

func generateStatsSummary(resultsDir, tablesDir string) error {
	path := filepath.Join(resultsDir, "latest-stats.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	var report struct {
		Comparisons []struct {
			PairLabel           string  `json:"pair_label"`
			Track               string  `json:"track"`
			Mode                string  `json:"mode"`
			Workload            string  `json:"workload"`
			ImplA               string  `json:"impl_a"`
			ImplB               string  `json:"impl_b"`
			Winner              string  `json:"winner"`
			Speedup             float64 `json:"speedup"`
			CI95Low             float64 `json:"ci95_low"`
			CI95High            float64 `json:"ci95_high"`
			PValue              float64 `json:"p_value"`
			PValueAdjusted      float64 `json:"p_value_adjusted"`
			EffectSizeCohenD    float64 `json:"effect_size_cohen_d"`
			SignificantBH       bool    `json:"significant_bh"`
			NoiseFloorMS        float64 `json:"noise_floor_ms"`
			MinObservableEffPct float64 `json:"min_observable_effect_pct"`
		} `json:"comparisons"`
	}
	if err := json.Unmarshal(data, &report); err != nil {
		return err
	}

	// Show only within-language e2e canonicalize comparisons (the key 28-comparison set).
	withinPairLabels := map[string]bool{
		"go:schubfach-vs-bd": true,
		"rs:schubfach-vs-bd": true,
	}

	var b strings.Builder
	b.WriteString("% Auto-generated by scripts/generate-paper-tables.go\n")
	b.WriteString("\\begin{table*}[htbp]\n")
	b.WriteString("\\caption{Within-language CLI comparisons (canonicalize mode; BH-significant marked with $^*$).}\n")
	b.WriteString("\\label{tab:stats-summary}\n")
	b.WriteString("\\centering\\small\n")
	b.WriteString("\\begin{tabular}{llllrrrrr}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Pair & Workload & Winner & Speedup & CI$_{95}$ & $p_\\text{adj}$ & $d$ & MDE (\\%) \\\\\n")
	b.WriteString("\\midrule\n")

	for _, c := range report.Comparisons {
		if !withinPairLabels[c.PairLabel] {
			continue
		}
		if c.Track != "e2e" || c.Mode != "canonicalize" {
			continue
		}
		sig := ""
		if c.SignificantBH {
			sig = "$^*$"
		}
		fmt.Fprintf(&b, "%s & %s & %s%s & %.2f$\\times$ & [%.3f, %.3f] & %.4f & %.2f & %.1f \\\\\n",
			escape(c.PairLabel), escape(c.Workload), c.Winner, sig, c.Speedup,
			c.CI95Low, c.CI95High, c.PValueAdjusted, c.EffectSizeCohenD, c.MinObservableEffPct)
	}

	b.WriteString("\\bottomrule\n")
	b.WriteString("\\multicolumn{8}{l}{\\footnotesize $^*$BH-significant at $q = 0.05$. $d$ = Cohen's $d$ ($\\bar{x}_A - \\bar{x}_B$)/$s_p$; negative = impl A faster.} \\\\\n")
	b.WriteString("\\multicolumn{8}{l}{\\footnotesize MDE = minimum detectable effect at 80\\% power. Full 247-comparison report in Appendix~\\ref{sec:appendix-tables}.} \\\\\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table*}\n")

	return os.WriteFile(filepath.Join(tablesDir, "stats-summary.tex"), []byte(b.String()), 0o644)
}

func mean(xs []float64) float64 {
	if len(xs) == 0 {
		return 0
	}
	var sum float64
	for _, x := range xs {
		sum += x
	}
	return math.Round(sum/float64(len(xs))*100) / 100
}

func trimCPUSuffix(s string) string {
	i := strings.LastIndex(s, "-")
	if i <= 0 || i+1 >= len(s) {
		return s
	}
	for _, r := range s[i+1:] {
		if r < '0' || r > '9' {
			return s
		}
	}
	return s[:i]
}

func parseBenchPrefix(prefix string) (impl, mode string, ok bool) {
	switch {
	case strings.HasPrefix(prefix, "BenchmarkAPICanonicalize"):
		mode = "canonicalize"
		p := strings.TrimPrefix(prefix, "BenchmarkAPICanonicalize")
		switch p {
		case "Schubfach":
			return "schubfach", mode, true
		case "JSONCanon":
			return "json-canon", mode, true
		case "SchubfachRs":
			return "schubfach-rs", mode, true
		case "JSONCanonRs":
			return "json-canon-rs", mode, true
		}
	case strings.HasPrefix(prefix, "BenchmarkAPIVerify"):
		mode = "verify"
		p := strings.TrimPrefix(prefix, "BenchmarkAPIVerify")
		switch p {
		case "Schubfach":
			return "schubfach", mode, true
		case "JSONCanon":
			return "json-canon", mode, true
		case "SchubfachRs":
			return "schubfach-rs", mode, true
		case "JSONCanonRs":
			return "json-canon-rs", mode, true
		}
	}
	return "", "", false
}

func indexHeader(row []string) map[string]int {
	m := make(map[string]int, len(row))
	for i, v := range row {
		m[v] = i
	}
	return m
}

func escape(s string) string {
	s = strings.ReplaceAll(s, "_", "\\_")
	s = strings.ReplaceAll(s, "&", "\\&")
	s = strings.ReplaceAll(s, "%", "\\%")
	return s
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}
